FROM node:22.12.0-alpine3.20

WORKDIR /rtchat-web

COPY turbo.json pnpm-workspace.yaml package.json .npmrc ./

COPY apps/web ./apps/web

COPY packages ./packages

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm run prisma:generate

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm run build

EXPOSE 3000

CMD [ "pnpm", "run", "start:web" ]
