name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Web App Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile.web
        push: true
        tags: sujal8976/rtchat-web:2.0
    
    - name: Build and Push WS App Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile.ws
        push: true
        tags: sujal8976/rtchat-ws:2.0

    - name: Verify Pushed Images
      run: |
        docker pull sujal8976/rtchat-web:2.0
       docker pull sujal8976/rtchat-ws:2.0

    - name: Clean Up Local Docker Images
      run: |
        docker images -q sujal8976/rtchat-web:2.0 | xargs -r docker rmi
       docker images -q sujal8976/rtchat-ws:2.0 | xargs -r docker rmi
